services:
  - type: web
    name: cyber-sentinel-backend
    env: docker
    buildCommand: ./gradlew build
    startCommand: java -jar build/libs/cyber-sentinel-backend-0.0.1-SNAPSHOT.jar
    dockerfilePath: Dockerfile
    plan: free